dbt_northwind_test:
  outputs:
    dev:
      dbname: postgres
      host: aws-0-us-east-1.pooler.supabase.com
      pass: YJYangela1137!
      port: 6543
      schema: public
      threads: 1
      type: postgres
      user: postgres.vadxutwjmyrqjqooqmcj
  target: dev
